FROM rust:alpine as builder

WORKDIR /backer

COPY . .

RUN echo -e http://mirrors.ustc.edu.cn/alpine/latest-stable/main/ > /etc/apk/repositories && apk update && apk add --no-cache -U musl-dev

RUN cp deploy/docker/rust-proxy-config.toml /usr/local/cargo/config.toml \
    && RUSTFLAGS="-D warnings" \
    && rustup override set nightly \
    && cargo clean \
    && cargo build --bin backer-server --release --target=x86_64-unknown-linux-musl

FROM alpine:latest

LABEL maintainer=duyunzhi<duyzmail@163.com>\
description="backer"

RUN echo -e http://mirrors.ustc.edu.cn/alpine/latest-stable/main/ > /etc/apk/repositories && apk update && apk add tzdata
RUN ln -sf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime
RUN echo 'Asia/Shanghai' >/etc/timezone

COPY --from=builder /backer/target/x86_64-unknown-linux-musl/release/backer-server /usr/local/bin/backer-server

ENTRYPOINT backer-server